apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-application-new
  title: ArgoCD Application new
  description: ArgoCD Application For ISD with Helm values override
  tags:
    - argo
    - helm
spec:
  owner: guests
  type: service
  parameters:
    - title: ArgoCD Configuration Options
      required:
        - name
        - config
      properties:
        apiVersion:
          default: argoproj.io/v1alpha1
          description: APIVersion for the resource
          type: string
          ui:readonly: true
        kind:
          default: Application
          description: Kind for the resource
          type: string
          ui:readonly: true
        name:
          type: string
          title: Application Name
          description: The name of the ArgoCD application.
          maxLength: 52
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          default: testappname
        namespace:
          description: Namespace for the resource
          type: string
          default: argocd
        config:
          type: object
          description: Configuration for the ArgoCD application
          properties:
            project:
              type: string
              default: default
            destination:
              type: object
              properties:
                namespace:
                  type: string
                  default: default
                server:
                  type: string
                  default: https://kubernetes.default.svc
            source:
              type: object
              properties:
                repoURL:
                  type: string
                  default: https://github.com/gopaljayanthi/appset-chart.git
                targetRevision:
                  type: string
                  default: HEAD
                path:
                  type: string
                  default: .
          required:
            - project
            - destination
            - source
  steps:
    - id: serialize
      name: Serialize Application Configuration
      action: roadiehq:utils:serialize:yaml
      input:
        data:
          apiVersion: ${{ parameters.apiVersion }}
          kind: ${{ parameters.kind }}
          metadata:
            name: ${{ parameters.name }}
            namespace: ${{ parameters.namespace }}
          spec: ${{ parameters.config }}
    - id: sanitize
      name: Sanitize Configuration
      action: cnoe:utils:sanitize
      input:
        document: ${{ steps['serialize'].output.serialized }}
    - id: write-values
      name: Write Helm Values Override
      action: roadiehq:utils:fs:write
      input:
        path: ./values.override.yaml
        content: ${{ parameters.config.source.valuesOverride }}
    - id: write-main-config
      name: Write Main YAML to File
      action: roadiehq:utils:fs:write
      input:
        path: ./app.yaml
        content: ${{ steps['sanitize'].output.sanitized }}
    - id: apply-main-config
      name: Apply Application Manifest
      action: cnoe:kubernetes:apply
      input:
        manifestPath: ./app.yaml
        namespaced: true
    - id: apply-values-override
      name: Apply Helm Values Override
      action: cnoe:kubernetes:apply
      input:
        manifestPath: ./values.override.yaml
        namespaced: true
