apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: helm-deployment
  title: Deploy Helm Chart
  description: A template to deploy a Helm chart using override values.
spec:
  owner: your-team
  type: service
  parameters:
    - title: Helm Chart Details
      properties:
        helmChart:
          title: Helm Chart Name
          type: string
          description: Specify the Helm chart to deploy (e.g., `nginx`).
        helmRepo:
          title: Helm Repository
          type: string
          description: Helm repository URL where the chart is hosted.
        namespace:
          title: Kubernetes Namespace
          type: string
          description: Namespace where the Helm chart will be deployed.
        overrideValues:
          title: Override Values
          type: string
          description: Enter override values in YAML format.
          ui:widget: textarea
  steps:
    - id: clone-repository
      name: Clone repository
      action: github:clone
      input:
        repoUrl: '{{ parameters.repoUrl }}'
        targetPath: './'
    - id: deploy-helm-chart
      name: Deploy Helm Chart
      action: custom:helm-deploy
      input:
        helmChart: '{{ parameters.helmChart }}'
        helmRepo: '{{ parameters.helmRepo }}'
        namespace: '{{ parameters.namespace }}'
        overrideValues: '{{ parameters.overrideValues }}'
